track: "a"
languages:
  - "eng"
checkpoint_path: "google-bert/bert-large-cased"
run_name: "bert-large-cased-eng"
training_params:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 5
  logging_dir: "./logs"
  logging_steps: 10
