track: "a"
languages:
  - "eng"
checkpoint_path: "facebook/bart-large-cnn"
run_name: "bart-large-cnn-eng2"
training_params:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 5
  logging_dir: "./logs"
  logging_steps: 10
num_beams: 1
repetition_penalty: 10
no_repeat_ngram_size: 3
